name: Release Build
'on':
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Build variant
        default: assembleLiveRelease
        options:
          - assembleLiveRelease
          - assembleSandRelease

jobs:
  build_and_archive:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/*.toml*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Environment google services
        if: ${{ inputs.variant == 'assembleSandRelease' }}
        run: |
          echo ${{ secrets.ENCODED_GOOGLE_SERVICES_SAND }} | base64 --decode >> app/src/sand/google-services.json

      - name: Environment google services
        if: ${{ inputs.variant == 'assembleLiveRelease' }}
        run: |
          echo ${{ secrets.ENCODED_GOOGLE_SERVICES_LIVE }} | base64 --decode >> app/src/live/google-services.json

      # Assemble AAB
      - name: Assemble bundle
        run: |
          ./gradlew :app:${{ inputs.variant }}

      # Sign AAB
      - name: Sign app
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: androidApp/build/outputs/apk/sand/release
          signingKeyBase64: ${{ secrets.ENCODED_KEYSTORE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      - name: Making build available
        id: artifact-upload-step
        uses: actions/upload-artifact@v7
        with:
          name: APK
          path: app/build/outputs/apk/**/*.apk
          retention-days: 2

      - name: Artifact info
        run: |
          echo "::notice::URL: ${{ steps.artifact-upload-step.outputs.artifact-url }} (${{ steps.artifact-upload-step.outputs.artifact-id }})"
